### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by PySimpleGUI** [Thomas9292/nasa-background#10]
Here's a version of your nasa_background.py file but with a GUI added instead of command line.

I was thinking that previewing the image would be an easy next step to add.  This could be done either with a "Preview" button in this window below that will popup a window with the image as a preview, or simply embedding the preview in the window itself.

Right now it simply displays the title and metadata.

![image](https://user-images.githubusercontent.com/46163555/71420886-b33deb80-2645-11ea-8088-c279a739d089.png)

```python
from tools import nasa_api, background
import PySimpleGUI as sg

def nasa_gui():
    '''Get the newest NASA Picture of the Day and set it as background'''
    meta_info = nasa_api.get_info()

    layout = [  [sg.Text(meta_info['title'], key='-TITLE-')],
                [sg.Text(meta_info["explanation"], size=(50,0), key='-DESCIPTION-')],
                [sg.Button('Set'), sg.Button('Cancel')]]
    window = sg.Window('NASA Picture of the Day', layout)
    event, values = window.read()
    window.close()
    if event == 'Set':
        file_path = nasa_api.download_image()
        background.change_background(file_path)


if __name__ == '__main__':
    nasa_gui()
```

**Comment by Thomas9292** [comment]
It's an interesting option, but not one we will be pursuing at this point. First, let's expand the functionality in the CLI format, which will be easy enough to use for most users on this community. Thank you for the input!
